START TRANSACTION;
DELETE FROM `Product` WHERE `id` NOT IN (SELECT `productId` FROM `OrderItem`);
UPDATE `Product` SET `name`='Juego de Cama Unicolor - Sencilla', `category`='Juego de Cama', `description`='Juego de cama unicolor elaborado 100% en poliéster, de textura suave y ligera. Ideal para uso diario gracias a su fácil lavado, secado rápido y resistencia al desgaste. Su diseño sencillo y elegante combina con cualquier estilo de habitación, brindando comodidad y practicidad.', `price`=89900, `image`='https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272313/juego_de_cama_unicolor_k4wpfx', `stock`=10, `colors`='Blanco, Negro, Gris', `size`='100x190 cm (Sencilla)' WHERE `id`=37;
UPDATE `Product` SET `name`='Juego de Cama Combinado - Sencilla', `category`='Juego de Cama', `description`='Juego de cama elaborado 100% en poliéster, de textura suave y ligera. Ideal para uso diario gracias a su fácil lavado, secado rápido y resistencia al desgaste. Su diseño sencillo y elegante combina con cualquier estilo de habitación, brindando comodidad y practicidad.', `price`=89900, `image`='https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272329/juego_de_cama_1_s638ja', `stock`=10, `colors`='Combinado', `size`='100x190 cm (Sencilla)' WHERE `id`=40;
UPDATE `Product` SET `name`='Cobija Polar Combinada - Sencilla', `category`='Cobijas', `description`='Las Cobijas Polar han sido diseñadas para ofrecer una experiencia superior de abrigo y confort. Confeccionadas en microfibra polar de alta densidad (210 g/m²), presentan una textura suave al tacto y un excelente poder térmico, garantizando calidez y comodidad en todo momento.', `price`=79900, `image`='https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272320/cobija_polar_combinada_k0adu8', `stock`=10, `colors`='Combinado', `size`='160x225 cm (Sencilla)' WHERE `id`=7;
UPDATE `Product` SET `name`='Toallas - Manos', `category`='Toallas', `description`='Confeccionada en 100% algodón de alta calidad, esta toalla ofrece una textura densa y suave al tacto, garantizando máxima absorción y durabilidad. Su gramaje de 570 g/m² proporciona una sensación de confort superior y un secado eficiente.', `price`=34000, `image`='https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272348/toallas_getsp2', `stock`=10, `colors`='Blanco, Gris oscuro', `size`='50x90 cm (Manos)' WHERE `id`=49;
INSERT INTO `Product` (`name`, `category`, `description`, `price`, `image`, `stock`, `colors`, `size`) VALUES
  ('Juego de Cama Unicolor - Doble', 'Juego de Cama', 'Juego de cama unicolor elaborado 100% en poliéster, de textura suave y ligera. Ideal para uso diario gracias a su fácil lavado, secado rápido y resistencia al desgaste. Su diseño sencillo y elegante combina con cualquier estilo de habitación, brindando comodidad y practicidad.', 99900, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272313/juego_de_cama_unicolor_k4wpfx', 10, 'Blanco, Negro, Gris', '140x190 cm (Doble)'),
  ('Juego de Cama Unicolor - Extra Doble', 'Juego de Cama', 'Juego de cama unicolor elaborado 100% en poliéster, de textura suave y ligera. Ideal para uso diario gracias a su fácil lavado, secado rápido y resistencia al desgaste. Su diseño sencillo y elegante combina con cualquier estilo de habitación, brindando comodidad y practicidad.', 109900, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272313/juego_de_cama_unicolor_k4wpfx', 10, 'Blanco, Negro, Gris', '160x190 cm (Extra Doble)'),
  ('Juego de Cama Combinado - Semidoble', 'Juego de Cama', 'Juego de cama elaborado 100% en poliéster, de textura suave y ligera. Ideal para uso diario gracias a su fácil lavado, secado rápido y resistencia al desgaste. Su diseño sencillo y elegante combina con cualquier estilo de habitación, brindando comodidad y practicidad.', 95000, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272332/juego_de_cama_5_d9squl', 10, 'Combinado', '120x190 cm (Semidoble)'),
  ('Juego de Cama Combinado - Doble', 'Juego de Cama', 'Juego de cama elaborado 100% en poliéster, de textura suave y ligera. Ideal para uso diario gracias a su fácil lavado, secado rápido y resistencia al desgaste. Su diseño sencillo y elegante combina con cualquier estilo de habitación, brindando comodidad y practicidad.', 99900, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272335/juego_de_cama_6_lnw8fe', 10, 'Combinado', '140x190 cm (Doble)'),
  ('Juego de Cama Combinado - Extra Doble', 'Juego de Cama', 'Juego de cama elaborado 100% en poliéster, de textura suave y ligera. Ideal para uso diario gracias a su fácil lavado, secado rápido y resistencia al desgaste. Su diseño sencillo y elegante combina con cualquier estilo de habitación, brindando comodidad y practicidad.', 119900, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272334/juego_de_cama_11_xppjkj', 10, 'Combinado', '160x190 cm (Extra Doble)'),
  ('Juego de Cama 4 Fundas - Doble', 'Juego de Cama', 'Juego de cama elaborado 100% en poliéster, de textura suave y ligera. Ideal para uso diario gracias a su fácil lavado, secado rápido y resistencia al desgaste. Su diseño sencillo y elegante combina con cualquier estilo de habitación, brindando comodidad y practicidad. Incluye 4 fundas.', 109900, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272312/juego_de_cama_9_m8fdpu', 10, 'Combinado', '140x190 cm (Doble)'),
  ('Cobija Polar Combinada - Doble', 'Cobijas', 'Las Cobijas Polar han sido diseñadas para ofrecer una experiencia superior de abrigo y confort. Confeccionadas en microfibra polar de alta densidad (210 g/m²), presentan una textura suave al tacto y un excelente poder térmico, garantizando calidez y comodidad en todo momento.', 89900, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272320/cobija_polar_combinada_k0adu8', 10, 'Combinado', '200x225 cm (Doble)'),
  ('Cobija Viajera - Estándar', 'Cobijas', 'Cobija viajera de grosor 280 g/m², ligera y suave al tacto. Brinda abrigo y confort en todo momento, ideal para viajes, hogar u oficina. Su textura resistente garantiza durabilidad y fácil mantenimiento.', 49900, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272321/cobija_viajera_1_ygmtbs', 10, 'Azul oscuro, Rojo, Gris oscuro', '130x150 cm (Estándar)'),
  ('Manta Polar - Estándar', 'Cobijas', 'Disfruta del máximo confort con la Manta Polar. Su tejido suave y cálido brinda una agradable sensación de bienestar, perfecta para acompañar tus momentos de descanso. Su diseño elegante y versátil complementa cualquier espacio del hogar, aportando estilo y calidez a salas, habitaciones y rincones de lectura.', 29900, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272302/cobija_polar_ynyrtx', 10, 'Azul oscuro, Beige', '130x150 cm (Estándar)'),
  ('Cobija Elite - Sencilla', 'Cobijas', 'Nuestra cobija Elite combina suavidad, elegancia y abrigo excepcional. Confeccionada en tela polar de alta calidad, brinda una textura suave al tacto y una calidez ideal para todo tipo de clima. Su acabado fino y resistente garantiza durabilidad y confort noche tras noche.', 199000, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272300/cobija_elite_1_gtj9uw', 10, 'Beige, Negro, Blanco', '160x220 cm (Sencilla)'),
  ('Cobija Elite - Doble', 'Cobijas', 'Nuestra cobija Elite combina suavidad, elegancia y abrigo excepcional. Confeccionada en tela polar de alta calidad, brinda una textura suave al tacto y una calidez ideal para todo tipo de clima. Su acabado fino y resistente garantiza durabilidad y confort noche tras noche.', 229000, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272319/cobija_elite_2_tkpmt6', 10, 'Beige, Negro, Blanco', '180x220 cm (Doble)'),
  ('Cobija Flannel - Sencilla', 'Cobijas', 'Cobija elaborada con tela flannel de alta calidad, con una textura extra suave, ligera y agradable al tacto. Proporciona la calidez ideal para un descanso confortable y es perfecta para regalar, combinando confort, calidad y estilo en un solo detalle.', 85000, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272320/cobija_flanell_1_tkzhhj', 10, 'Café, Gris, Beige, Lila', '160x220 cm (Sencilla)'),
  ('Cobija Flannel - Doble', 'Cobijas', 'Cobija elaborada con tela flannel de alta calidad, con una textura extra suave, ligera y agradable al tacto. Proporciona la calidez ideal para un descanso confortable y es perfecta para regalar, combinando confort, calidad y estilo en un solo detalle.', 95000, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272301/cobija_flanell_2_mflb4y', 10, 'Negro, Gris, Blanco, Verde', 'Doble'),
  ('Toallas - Cuerpo', 'Toallas', 'Confeccionada en 100% algodón de alta calidad, esta toalla ofrece una textura densa y suave al tacto, garantizando máxima absorción y durabilidad. Su gramaje de 570 g/m² proporciona una sensación de confort superior y un secado eficiente.', 69900, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272348/toallas_getsp2', 10, 'Blanco, Gris oscuro', '70x140 cm (Cuerpo)'),
  ('Toallas - Kit', 'Toallas', 'Confeccionada en 100% algodón de alta calidad, esta toalla ofrece una textura densa y suave al tacto, garantizando máxima absorción y durabilidad. Su gramaje de 570 g/m² proporciona una sensación de confort superior y un secado eficiente.', 99900, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272348/toallas_getsp2', 10, 'Blanco, Gris oscuro', 'Kit (Manos y Cuerpo)'),
  ('Almohada Dúo con Embone - Estándar', 'Almohadas', 'La Almohada Dúo con Embone está diseñada para ofrecer un descanso cómodo y confortable. Su relleno de fibra de poliéster siliconada proporciona una sensación suave y esponjosa, mientras que su diseño con embone brinda un mejor acabado, mayor resistencia y una excelente conservación de la forma.', 120000, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790273325/almohada_duo_bvhzz6', 10, 'Blanco', '50x70 cm'),
  ('Almohada Classic - Estándar', 'Almohadas', 'La Almohada Classic Doble Forro está diseñada para brindar una experiencia de descanso cómoda y placentera. Su relleno de fibra de poliéster siliconada proporciona una sensación suave y esponjosa, mientras que su doble forro aporta mayor resistencia y prolonga la vida útil del producto.', 49900, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790273325/almohada_clasic_wrpgxk', 10, 'Blanco', '50x70 cm'),
  ('Almohada Plus - Estándar', 'Almohadas', 'La Almohada Plus Doble Forro con Embone está diseñada para brindar un descanso cómodo y reparador. Su relleno de fibra de poliéster siliconada ofrece una sensación suave y esponjosa, mientras que el doble forro con embone aporta mayor resistencia y durabilidad.', 59900, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272300/almohada_plus_n8vij2', 10, 'Blanco', '50x70 cm'),
  ('Almohada Elite - Estándar', 'Almohadas', 'La Almohada Elite Line Doble Forro Premium está diseñada para quienes valoran el confort, la calidad y el bienestar en cada detalle. Su exclusivo diseño acolchado y su relleno de fibra siliconada de alta calidad ofrecen una sensación de suavidad envolvente durante toda la noche.', 74900, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272299/almohada_elite_dfvjnw', 10, 'Blanco', '50x70 cm'),
  ('Quilt Doble Faz - Sencillo', 'Quilts', 'Confeccionado con materiales de alta calidad y un delicado acolchado que brinda suavidad y confort, este quilt doble faz combina elegancia, funcionalidad y durabilidad. Su diseño reversible permite disfrutar de dos estilos diferentes en una sola pieza.', 115000, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272345/quilt_sencillo_1_vu4dqx', 10, 'Surtidos', '170x230 cm (Sencillo)'),
  ('Quilt Doble Faz - Doble', 'Quilts', 'Confeccionado con materiales de alta calidad y un delicado acolchado que brinda suavidad y confort, este quilt doble faz combina elegancia, funcionalidad y durabilidad. Su diseño reversible permite disfrutar de dos estilos diferentes en una sola pieza.', 125000, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272349/quilt_doble_1_loxmdq', 10, 'Surtidos', '220x230 cm (Doble)'),
  ('Quilt Doble Faz - Extra Doble', 'Quilts', 'Confeccionado con materiales de alta calidad y un delicado acolchado que brinda suavidad y confort, este quilt doble faz combina elegancia, funcionalidad y durabilidad. Su diseño reversible permite disfrutar de dos estilos diferentes en una sola pieza.', 135000, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272337/quilt_extra_1_y82jzz', 10, 'Surtidos', '240x240 cm (Extra Doble)'),
  ('Quilt Estampado - Estándar', 'Quilts', 'Confeccionado con materiales de alta calidad y un delicado acolchado que brinda suavidad y confort, este quilt doble faz combina elegancia, funcionalidad y durabilidad. Su diseño reversible permite disfrutar de dos estilos diferentes en una sola pieza.', 99900, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272347/quilt_sencillo_6_a3zwex', 10, 'Surtidos', '170x250 cm'),
  ('Cojines Bordados - Estándar', 'Cojines', 'Elaborados con materiales de alta calidad, nuestros cojines 100% bordados a mano destacan por sus acabados artesanales, elegancia y exclusividad. Cada pieza aporta textura, sofisticación y un estilo único para realzar cualquier espacio.', 95000, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272304/cojines_bordados_bntpu7', 10, 'Surtidos', '45x45 cm'),
  ('Cojín Peluche - Estándar', 'Cojines', 'Fabricados con materiales de alta calidad, nuestros cojines peludos ofrecen una textura extra suave y un acabado elegante que aporta calidez y confort a cualquier espacio. Ideales para salas, habitaciones y áreas de descanso.', 35000, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272303/cojin_peluche_1_zcgr1j', 10, 'Surtidos', '45x45 cm'),
  ('Protector de Colchón Impermeable - Sencillo', 'Protectores', 'El Protector de Colchón Impermeable Fenissa Classic presenta un diseño limpio y sofisticado que se integra perfectamente en cualquier ambiente. Su acabado en color blanco transmite sensación de frescura, higiene y bienestar.', 79900, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272318/protector_de_colchon_yickwa', 10, 'Blanco', '100x190 cm (Sencillo)'),
  ('Protector de Colchón Impermeable - Doble', 'Protectores', 'El Protector de Colchón Impermeable Fenissa Classic presenta un diseño limpio y sofisticado que se integra perfectamente en cualquier ambiente. Su acabado en color blanco transmite sensación de frescura, higiene y bienestar.', 89900, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272318/protector_de_colchon_yickwa', 10, 'Blanco', '140x190 cm (Doble)'),
  ('Protector de Colchón Impermeable - Extra Doble', 'Protectores', 'El Protector de Colchón Impermeable Fenissa Classic presenta un diseño limpio y sofisticado que se integra perfectamente en cualquier ambiente. Su acabado en color blanco transmite sensación de frescura, higiene y bienestar.', 99900, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272318/protector_de_colchon_yickwa', 10, 'Blanco', '160x200 cm (Extra Doble)'),
  ('Edredón - Sencillo', 'Edredones', 'Este edredón es una opción funcional y decorativa para complementar la habitación. Gracias a su diseño moderno, su textura suave y su fácil mantenimiento, es ideal para quienes buscan comodidad y practicidad sin dejar de lado la estética del hogar.', 125000, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272327/edredon_sencillo_1_seopv8', 10, 'Surtidos', '170x240 cm (Sencillo)'),
  ('Edredón - Doble', 'Edredones', 'Este edredón es una opción funcional y decorativa para complementar la habitación. Gracias a su diseño moderno, su textura suave y su fácil mantenimiento, es ideal para quienes buscan comodidad y practicidad sin dejar de lado la estética del hogar.', 135000, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272305/edredon_doble_1_ov5lbo', 10, 'Surtidos', '220x240 cm (Doble)'),
  ('Edredón - Extra Doble', 'Edredones', 'Este edredón es una opción funcional y decorativa para complementar la habitación. Gracias a su diseño moderno, su textura suave y su fácil mantenimiento, es ideal para quienes buscan comodidad y practicidad sin dejar de lado la estética del hogar.', 145000, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272327/edredon_extra_doble_1_jodgmk', 10, 'Surtidos', '240x240 cm (Extra Doble)'),
  ('Plumón - Doble', 'Plumones y Duvets', 'Disfruta del confort y la suavidad de este plumón para cama, diseñado para brindar una sensación acogedora, ligera y elegante. Su acabado acolchado aporta volumen, abrigo y una apariencia limpia que transforma la cama en un espacio más cómodo y armonioso.', 149900, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272314/plumon_1_hmzarm', 10, 'Surtidos', '210x240 cm (Doble)'),
  ('Duvet Nevado - Doble', 'Plumones y Duvets', 'Dale un toque de elegancia y confort a tu habitación con nuestros duvets Fenissa. Diseños modernos, versátiles y decorativos, elaborados en tela suave al tacto, ideales para renovar tus espacios con estilo, abrigo y comodidad.', 169900, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272326/duvet_nevado_1_uh6rlx', 10, 'Surtidos', '210x240 cm (Doble)'),
  ('Duvet Unicolor - Doble', 'Plumones y Duvets', 'Su diseño moderno y sofisticado permite combinarlo con diferentes estilos de decoración, aportando calidez, frescura y armonía a tu dormitorio. Además, cuenta con una presentación práctica.', 129900, 'https://res.cloudinary.com/dvrz5uflr/image/upload/f_auto,q_auto,w_1200/v1790272305/duvet_unicolor_1_iefkyr', 10, 'Surtidos', '210x240 cm (Doble)');
COMMIT;
