import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();
const DOMAIN = "https://insumos360.com"; 

async function main() {
  await prisma.product.createMany({
    data: [
      {
        name: "Juego de Cama Unicolor - Sencilla",
        category: "Juego de Cama",
        description: "100% Poliéster. Unicolor, sencillo y elegante. Textura suave y ligera.",
        price: 82000,
        image: `${DOMAIN}/productos/cama-unicolor.jpg`,
        stock: 15,
        colors: "Blanco, Negro, Gris",
        size: "100x190 cm (Sencilla)",
      },
      {
        name: "Juego de Cama Unicolor - Doble",
        category: "Juego de Cama",
        description: "100% Poliéster. Unicolor, sencillo y elegante. Textura suave y ligera.",
        price: 94050,
        image: `${DOMAIN}/productos/cama-unicolor.jpg`,
        stock: 15,
        colors: "Blanco, Negro, Gris",
        size: "140x190 cm (Doble)",
      },
      {
        name: "Juego de Cama Unicolor - Extra Doble",
        category: "Juego de Cama",
        description: "100% Poliéster. Unicolor, sencillo y elegante. Textura suave y ligera.",
        price: 103500,
        image: `${DOMAIN}/productos/cama-unicolor.jpg`,
        stock: 15,
        colors: "Blanco, Negro, Gris",
        size: "160x190 cm (Extra Doble)",
      },
      {
        name: "Juego de Cama Combinada - Sencilla",
        category: "Juego de Cama",
        description: "100% Poliéster. Colores armónicos para dar un toque moderno y elegante.",
        price: 82200,
        image: `${DOMAIN}/productos/cama-combinada.jpg`,
        stock: 15,
        colors: "Combinado",
        size: "100x190 cm (Sencilla)",
      },
      {
        name: "Juego de Cama Combinada - Doble",
        category: "Juego de Cama",
        description: "100% Poliéster. Colores armónicos para dar un toque moderno y elegante.",
        price: 94050,
        image: `${DOMAIN}/productos/cama-combinada.jpg`,
        stock: 15,
        colors: "Combinado",
        size: "140x190 cm (Doble)",
      },
      {
        name: "Juego de Cama Combinada - Extra Doble",
        category: "Juego de Cama",
        description: "100% Poliéster. Colores armónicos para dar un toque moderno y elegante.",
        price: 103500,
        image: `${DOMAIN}/productos/cama-combinada.jpg`,
        stock: 15,
        colors: "Combinado",
        size: "160x190 cm (Extra Doble)",
      },
      {
        name: "Cobija Polar Combinada - Sencilla",
        category: "Cobijas",
        description: "100% Poliéster. Microfibra polar de alta densidad (210 g/m2).",
        price: 76150,
        image: `${DOMAIN}/productos/cobija-polar.jpg`,
        stock: 10,
        colors: "Combinado",
        size: "160x225 cm (Sencilla)",
      },
      {
        name: "Cobija Polar Combinada - Doble",
        category: "Cobijas",
        description: "100% Poliéster. Microfibra polar de alta densidad (210 g/m2).",
        price: 87850,
        image: `${DOMAIN}/productos/cobija-polar.jpg`,
        stock: 10,
        colors: "Combinado",
        size: "200x225 cm (Doble)",
      },
      {
        name: "Cobija Viajera - Estándar",
        category: "Cobijas",
        description: "100% Poliéster. Grosor 280 g/m2. Ligera, cálida y confortable.",
        price: 44900,
        image: `${DOMAIN}/productos/cobija-viajera.jpg`,
        stock: 50,
        colors: "Azul oscuro, Rojo, Gris oscuro, Café, Gris claro, Rosa, Beige, Naranja, Azul rey",
        size: "130x150 cm (Estándar)",
      },
      {
        name: "Cobija Elite - Sencilla",
        category: "Cobijas",
        description: "100% Poliéster. Suave al tacto, ligera y de abrigo excepcional.",
        price: 201500,
        image: `${DOMAIN}/productos/cobija-elite.jpg`,
        stock: 5,
        colors: "Surtidos",
        size: "160x220 cm (Sencilla)",
      },
      {
        name: "Cobija Elite - Doble",
        category: "Cobijas",
        description: "100% Poliéster. Suave al tacto, ligera y de abrigo excepcional.",
        price: 234500,
        image: `${DOMAIN}/productos/cobija-elite.jpg`,
        stock: 5,
        colors: "Surtidos",
        size: "180x220 cm (Doble)",
      },
      {
        name: "Cobija Elite - Extra Doble",
        category: "Cobijas",
        description: "100% Poliéster. Suave al tacto, ligera y de abrigo excepcional.",
        price: 259500,
        image: `${DOMAIN}/productos/cobija-elite.jpg`,
        stock: 5,
        colors: "Surtidos",
        size: "220x220 cm (Extra Doble)",
      },
      {
        name: "Toallas - Manos",
        category: "Toallas",
        description: "Algodón 100%. Suave, absorbente y resistente al lavado.",
        price: 38400,
        image: `${DOMAIN}/productos/toallas.jpg`,
        stock: 20,
        colors: "Blanco, Gris oscuro",
        size: "50x90 cm (Manos)",
      },
      {
        name: "Toallas - Cuerpo",
        category: "Toallas",
        description: "Algodón 100%. Suave, absorbente y resistente al lavado.",
        price: 79500,
        image: `${DOMAIN}/productos/toallas.jpg`,
        stock: 20,
        colors: "Blanco, Gris oscuro",
        size: "70x140 cm (Cuerpo)",
      },
      {
        name: "Toallas - Set x2",
        category: "Toallas",
        description: "Algodón 100%. Suave, absorbente y resistente al lavado.",
        price: 107850,
        image: `${DOMAIN}/productos/toallas.jpg`,
        stock: 12,
        colors: "Blanco, Gris oscuro",
        size: "Set x2 (Manos y Cuerpo)",
      },
      {
        name: "Tapete Rectangular - Estándar",
        category: "Tapetes",
        description: "Antiadherente. Diseños modernos y funcionales.",
        price: 35700,
        image: `${DOMAIN}/productos/tapete-rectangular.jpg`, 
        stock: 15,
        colors: "Único",
        size: "38x68 cm (Estándar)",
      },
      {
        name: "Tapete Ovalado - Estándar",
        category: "Tapetes",
        description: "Antiadherente. Diseños modernos y funcionales.",
        price: 35700,
        image: `${DOMAIN}/productos/tapete-ovalado.jpg`, 
        stock: 15,
        colors: "Único",
        size: "38x68 cm (Estándar)",
      },
      {
        name: "Tapete Rectangular Largo (Cookin Time) - Set",
        category: "Tapetes",
        description: "Antiadherente. Set ideal para espacios de cocina.",
        price: 84650,
        image: `${DOMAIN}/productos/tapete-cocina.jpg`, 
        stock: 10,
        colors: "Diseño Cocina",
        size: "38x68 y 40x120 cm (Set)",
      }
    ],
  });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });